theme: jekyll-theme-minimal

title: Zhennan(Leo) Wu
description: Hello! I am a Ph.D. student of computer science at Indiana University Bloomington. I am adviced by Roni Khardon.
             My research interests lie in Reinforcement Learning. Currently I am working on planning as inference.
logo: https://github.com/Zhennan-Wu/zhennanwu.github.io/blob/gh-pages/IMG_4470.JPG
